services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=customer_db'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}'
      - 'POSTGRES_USER=${DB_USER:-postgres}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  customer-service:
    image: ${DOCKER_REGISTRY:-localhost}/digital-bank/customer-service:${TAG:-latest}
    ports:
      - '${PORT:-9000}:9000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer_db'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USER:-postgres}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-postgres}'
      - 'APP_FILE_UPLOAD_DIR=/home/spring/uploads'
      - 'APP_FILE_BASE_URL=${BASE_URL:-http://localhost:9000}/api/files'
    volumes:
      - upload-data:/home/spring/uploads
    restart: unless-stopped

volumes:
  postgres-data:
  upload-data: